### PR TITLE
Update EC code names for most recent templates

### PR DESCRIPTION
**Pull request by trumanc**
Got reports of 2 EC codes that weren't being recognized when partners tried to upload their files in https://github.com/usdigitalresponse/arpa-reporter/issues/419

I combed through all the bulk upload templates to find other cases of mismatches (did cmd-f searches for each string exactly as it appeared in the template) and found those two cases, plus 8 more mismatches.

~Note: Still waiting for an answer about code 2.34. The template includes a tab space in the name, and I'm unsure if it should be included or not~

Looks like uploads work with or without the trailing whitespace, so I've omitted it here.
Screen Shot 2022-07-12 at 11 04 54 AM
.

### CODE REVIEW

**Comment by igor47** [comment]
we probably want to support the older templates that are circulating out there, too. we can make the list canonical, but now those older sheets will fail validation. i suggest also relaxing the validation criteria -- here, maybe it means just ignoring `'` and `,` characters, like we do with drop-list validation in https://github.com/usdigitalresponse/arpa-reporter/blob/3c43cf1c230eba7f03c1f3709e4b744e4521512e/src/server/services/validation-rules.js#L36-L38 ?

not sure what to do about the lead one, maybe we can keep both strings in the code somehow? or maybe we don't even care about the string, and we can just extract the numeric code at the beginning and that's okay?

**Comment by trumanc** [comment]
This is further complicated by not knowing exactly what values the bulk upload endpoint will allow ultimately. Since we almost certainly won't be able to keep the input templates exactly correct (and users will likely be using old/out-of-date templates anyways), Joe has suggested in https://github.com/usdigitalresponse/arpa-reporter/issues/419#issuecomment-1182639779 that the users might just have to send the files to admins to correct EC codes when something is wrong.
With that in mind:

I've relaxed the validation by changing the error to be a warning if the code name doesn't exactly match. It also includes some additional messaging that the code might need to be corrected for full submission, even if it doesn't fail the current validation. This will allow people to continue to use old templates, but at least get some warning that it being out-of-date might cause them issues further down.

**Comment by ajhyndman** [comment]
I think this is an improvement, and I'm happy to land it!

I actually think we could probably get away with only verifying that the numeric code matches a known code, and ignoring any other mismatch.

Then, in the report generation stage, we can map the EC code back to a single source of truth string that is defined in code.

**Review by ajhyndman — APPROVED** [review]

**Comment by trumanc** [comment]
Yeah, I was thinking it would be nice to just do the mapping when generating output. My biggest worry is that if our source-of-truth is off then it would be pretty annoying if we actually altered someone's correct input to be something incorrect...

**Pull request merged**
